version: "2"

linters:
  enable:
    - staticcheck
    - govet
    - unused
    - revive
    - gosec
    - errorlint

formatters:
  enable:
    - gofumpt
    - gofmt
    - goimports

linters-settings:
  staticcheck:
    checks: ["all"]

formatters-settings:
  gofumpt:
    extra-rules: true
